/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaptainRouteImport } from './routes/captain'
import { Route as CashierTreasuryRouteImport } from './routes/cashier-treasury'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OvenRouteImport } from './routes/oven'
import { Route as PosRouteImport } from './routes/pos'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminHrRouteImport } from './routes/admin/hr'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLedgerRouteImport } from './routes/admin/ledger'
import { Route as AdminMallRouteImport } from './routes/admin/mall'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminReceiptsRouteImport } from './routes/admin/receipts'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRestaurantRouteImport } from './routes/admin/restaurant'
import { Route as AdminSystemUpdateRouteImport } from './routes/admin/system-update'
import { Route as AdminUsersRouteImport } from './routes/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainRoute = CaptainRouteImport.update({
  id: '/captain',
  path: '/captain',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierTreasuryRoute = CashierTreasuryRouteImport.update({
  id: '/cashier-treasury',
  path: '/cashier-treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OvenRoute = OvenRouteImport.update({
  id: '/oven',
  path: '/oven',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMallRoute = AdminMallRouteImport.update({
  id: '/mall',
  path: '/mall',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantRoute = AdminRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemUpdateRoute = AdminSystemUpdateRouteImport.update({
  id: '/system-update',
  path: '/system-update',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/captain': typeof CaptainRoute
  '/cashier-treasury': typeof CashierTreasuryRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/oven': typeof OvenRoute
  '/pos': typeof PosRoute
  '/setup': typeof SetupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/mall': typeof AdminMallRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/system-update': typeof AdminSystemUpdateRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captain': typeof CaptainRoute
  '/cashier-treasury': typeof CashierTreasuryRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/oven': typeof OvenRoute
  '/pos': typeof PosRoute
  '/setup': typeof SetupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/mall': typeof AdminMallRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/system-update': typeof AdminSystemUpdateRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/captain': typeof CaptainRoute
  '/cashier-treasury': typeof CashierTreasuryRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/oven': typeof OvenRoute
  '/pos': typeof PosRoute
  '/setup': typeof SetupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/mall': typeof AdminMallRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/restaurant': typeof AdminRestaurantRoute
  '/admin/system-update': typeof AdminSystemUpdateRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/captain'
    | '/cashier-treasury'
    | '/components'
    | '/login'
    | '/menu'
    | '/oven'
    | '/pos'
    | '/setup'
    | '/admin/accounts'
    | '/admin/hr'
    | '/admin/inventory'
    | '/admin/ledger'
    | '/admin/mall'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/restaurant'
    | '/admin/system-update'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captain'
    | '/cashier-treasury'
    | '/components'
    | '/login'
    | '/menu'
    | '/oven'
    | '/pos'
    | '/setup'
    | '/admin/accounts'
    | '/admin/hr'
    | '/admin/inventory'
    | '/admin/ledger'
    | '/admin/mall'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/restaurant'
    | '/admin/system-update'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/captain'
    | '/cashier-treasury'
    | '/components'
    | '/login'
    | '/menu'
    | '/oven'
    | '/pos'
    | '/setup'
    | '/admin/accounts'
    | '/admin/hr'
    | '/admin/inventory'
    | '/admin/ledger'
    | '/admin/mall'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/restaurant'
    | '/admin/system-update'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaptainRoute: typeof CaptainRoute
  CashierTreasuryRoute: typeof CashierTreasuryRoute
  ComponentsRoute: typeof ComponentsRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OvenRoute: typeof OvenRoute
  PosRoute: typeof PosRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain': {
      id: '/captain'
      path: '/captain'
      fullPath: '/captain'
      preLoaderRoute: typeof CaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier-treasury': {
      id: '/cashier-treasury'
      path: '/cashier-treasury'
      fullPath: '/cashier-treasury'
      preLoaderRoute: typeof CashierTreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oven': {
      id: '/oven'
      path: '/oven'
      fullPath: '/oven'
      preLoaderRoute: typeof OvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mall': {
      id: '/admin/mall'
      path: '/mall'
      fullPath: '/admin/mall'
      preLoaderRoute: typeof AdminMallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurant': {
      id: '/admin/restaurant'
      path: '/restaurant'
      fullPath: '/admin/restaurant'
      preLoaderRoute: typeof AdminRestaurantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-update': {
      id: '/admin/system-update'
      path: '/system-update'
      fullPath: '/admin/system-update'
      preLoaderRoute: typeof AdminSystemUpdateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminMallRoute: typeof AdminMallRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRestaurantRoute: typeof AdminRestaurantRoute
  AdminSystemUpdateRoute: typeof AdminSystemUpdateRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminHrRoute: AdminHrRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminMallRoute: AdminMallRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRestaurantRoute: AdminRestaurantRoute,
  AdminSystemUpdateRoute: AdminSystemUpdateRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CaptainRoute: CaptainRoute,
  CashierTreasuryRoute: CashierTreasuryRoute,
  ComponentsRoute: ComponentsRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OvenRoute: OvenRoute,
  PosRoute: PosRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
